### ISSUE TITLE
Confusing branches

### ISSUE THREAD

**Issue by lemonadee71** [bappyasif/edutainment_game_based_on_animal_trivia#5]
It's not very clear on what branch we should work on. Like on the latest commit, the changes in layout are reflected on the master so now the `layouts-and-json-drafts` branch is two commits behind (excluding duplicate and unrelated commits). At the same time, the changes in JSON are not reflected on the `master` so the `layouts-and-json-drafts` is also ahead for that matter. The JSON is updated there because I thought that's the branch we should work on for drafts. 

I think there are no conflicts but it's quite confusing to work on.

~~Edit: I already cherry picked the changes to the other branches to reflect the changes but I still think we should work on just a specific branch like for layouts.~~
Edit: I reverted the changes for now. I'd like to know what your thoughts are first on how we'll approach this @bappyasif

**Comment by bappyasif** [comment]
it seems, i wasn't paying attention these, lets talk about these and clean up our branches, thanks @lemonadee71
